/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SportSlugLazyImport = createFileRoute('/$sportSlug')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SportSlugLazyRoute = SportSlugLazyImport.update({
  id: '/$sportSlug',
  path: '/$sportSlug',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$sportSlug.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$sportSlug': {
      id: '/$sportSlug'
      path: '/$sportSlug'
      fullPath: '/$sportSlug'
      preLoaderRoute: typeof SportSlugLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$sportSlug': typeof SportSlugLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$sportSlug': typeof SportSlugLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$sportSlug': typeof SportSlugLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$sportSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$sportSlug'
  id: '__root__' | '/' | '/$sportSlug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SportSlugLazyRoute: typeof SportSlugLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SportSlugLazyRoute: SportSlugLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$sportSlug"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$sportSlug": {
      "filePath": "$sportSlug.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
